---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":robot:"
    assignees:
      - spixx
    labels:
      - ":robot: Github Actions"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      versions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":snake:"
    assignees:
      - spixx
    labels:
      - ":snake: Python"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      versions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

...
